[browser]
serverAddress = '0.0.0.0'

# Internet address where users should point their browsers in order to connect to the app. Can be IP address or DNS name and path.
# This is used to: - Set the correct URL for CORS and XSRF protection purposes. - Show the URL on the terminal - Open the browser - Tell the browser where to connect to the server when in liveSave mode.
# Default: 'localhost'


# Whether to send usage statisics to Streamlit.
# Default: true

gatherUsageStats = true


[global]
dataFrameSerialization = "legacy"

[theme]
base="dark"
primaryColor="#4be8e0"